---
driver:
  name: vagrant

provisioner:
  name: policyfile_zero

verifier:
  name: inspec


platforms:
  - name: ubuntu-16.04
  - name: windows2016
    driver_config: 
      box: mwrock/Windows2016

suites:
  - name: master
    includes:
      - ubuntu-16.04
    provisioner:
      policyfile: jenkins-master.rb
    verifier:
      inspec_tests:
        - test/integration/master
  - name: agent
    includes:
      - windows2016
    provisioner:
      policyfile: jenkins-agent.rb
    verifier:
      inspec_tests:
        - test/integration/agent
