name 'cafe-build'
maintainer 'Annie Hedgpeth'
maintainer_email 'annie.hedgpeth@gmail.com'
license 'all_rights'
description 'Installs/Configures cafe-build'
long_description 'Installs/Configures cafe-build'
version '0.1.0'

depends 'docker', '~> 2.0'
depends 'jenkins'
depends 'windows'
depends 'chocolatey'
depends 'docker', '~> 2.13.10'
depends 'apt'
